# ./prometheus/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['webapp:5000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:9323']
